{
    'name': 'Employee Valuation',
    'version': '14.0.1.0.0',
    'summary': 'Employee Valuation',
    'sequence': 10,
    'description': "Employee Valuation",
    'category': 'Human Resources',
    'website': 'https://www.catalisterp.com/',
    'depends': ['base', 'hr'],
    'data': ['security/ir.model.access.csv',
             'security/security.xml',
             'data/sequence.xml',
             'views/hr_department.xml',
             'views/performance_criteria.xml',
             'views/hr_employee.xml',
             'views/employee_valuation.xml',
             'views/performance_assessment.xml'
             ],
    'demo': [],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
