{
    'name': 'Production planning',
    'version': '14.0.1.0.0',
    'category': 'Production',
    'summary': 'Production planning for kitchens',
    'author': 'Divergent Catalist ERP Solutions',
    'company': 'Divergent Catalist ERP Solutions',
    'maintainer': 'Divergent Catalist ERP Solutions',
    'website': 'https://www.catalisterp.com/',
    'depends': ['base', 'mrp', 'stock', 'sale_management',
                'uom'],

    'data': ['security/ir.model.access.csv',
             'security/security.xml',
             'data/trip_name.xml',
             'data/sequence.xml',
             'views/production_planning.xml'],
    'qweb': [],
    'license': 'LGPL-3',
    'installable': True,
    'application': False,
    'auto_install': False,
}
