# -*- coding: utf-8 -*-
{'name': ' Discount Sales ',
 'version': '14.0.1.0.0',
 'summary': 'Discount Sales Configurations',
 'category': 'Tools',
 'author': 'Catalist Divergent ERP',
 'maintainer': 'Catalist Divergent ERP',
 'company': 'Catalist Divergent ERP',
 'website': 'https://www.catalisterp.com/',
 'depends': ['base', 'sale', 'sale_management'],
 'data': [
          # 'views/new_company_view.xml',
          'views/so_view.xml',
          ],
 'images': [],
 'license': 'AGPL-3',
 'installable': True,
 'application': False,
 'auto_install': False,
 }